 // File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd2yXeP9VMzRoD961WSpAfdHFBgIftogU',
    appId: '1:172881875812:web:9e4809d1e8148d55eba071',
    messagingSenderId: '172881875812',
    projectId: 'ticket-d5d35',
    authDomain: 'ticket-d5d35.firebaseapp.com',
    databaseURL: 'https://ticket-d5d35-default-rtdb.firebaseio.com',
    storageBucket: 'ticket-d5d35.appspot.com',
    measurementId: 'G-MT76D27HG1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1wo0fgUv0h9prvz1mt5wMc3Lvofxzs8w',
    appId: '1:172881875812:ios:616e086f8eb59550eba071',
    messagingSenderId: '172881875812',
    projectId: 'ticket-d5d35',
    databaseURL: 'https://ticket-d5d35-default-rtdb.firebaseio.com',
    storageBucket: 'ticket-d5d35.appspot.com',
    iosBundleId: 'com.ticketmaster.caleboruta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1wo0fgUv0h9prvz1mt5wMc3Lvofxzs8w',
    appId: '1:172881875812:ios:b0936bb3485c5ce1eba071',
    messagingSenderId: '172881875812',
    projectId: 'ticket-d5d35',
    databaseURL: 'https://ticket-d5d35-default-rtdb.firebaseio.com',
    storageBucket: 'ticket-d5d35.appspot.com',
    iosBundleId: 'com.example.ticketmaster',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTERYYBxfPGgpZg9F2jbxz667UQoljFHo',
    appId: '1:172881875812:android:3a49472b2b4af2d8eba071',
    messagingSenderId: '172881875812',
    projectId: 'ticket-d5d35',
    databaseURL: 'https://ticket-d5d35-default-rtdb.firebaseio.com',
    storageBucket: 'ticket-d5d35.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd2yXeP9VMzRoD961WSpAfdHFBgIftogU',
    appId: '1:172881875812:web:aae03dc2c327f3d6eba071',
    messagingSenderId: '172881875812',
    projectId: 'ticket-d5d35',
    authDomain: 'ticket-d5d35.firebaseapp.com',
    databaseURL: 'https://ticket-d5d35-default-rtdb.firebaseio.com',
    storageBucket: 'ticket-d5d35.appspot.com',
    measurementId: 'G-NH0YS66Y6P',
  );

}